### ISSUE TITLE
Popular/New Releases - Design User Interface

### ISSUE THREAD

**Issue by SBRUCEORTIZ** [CEN4010-Fall2023-Prin-Soft-Eng/cen4010-prin-soft-eng-final-project-002-group-6#24]
![Image](https://github.com/CEN4010-Fall2023-Prin-Soft-Eng/cen4010-prin-soft-eng-final-project-final-project-002-group-6/assets/116595993/de7fcd42-b3cc-4c96-a6f6-bd3ef171ba36)

**Comment by shahmeerxkhan** [comment]
Design Interface of homepage
